### ISSUE TITLE
Possibility to highlight the mentions (without href)

### ISSUE THREAD

**Issue by tonymarkoc** [AnthonyNahas/ngx-linkifyjs#116]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality
To add the possibility only to highlight the mentions. For example i want to have them highlighted in yellow (or just surround them with \<mark\> attributes). Currently i can only enable them, which will make them clickable and they will navigate to the certain URL.

**Comment by AnthonyNahas** [comment]
this would be impossible since we are relying on linkifyjs natively...

I am sorry!
