### ISSUE TITLE
Change href to [routerLink]

### ISSUE THREAD

**Issue by sidjai09** [AnthonyNahas/ngx-linkifyjs#119]
```
- [x] bug report -> please search issues before submitting
- [x] feature request
```

### OS and Version
Windows 7

### Versions
node : v10.15.3
npm : v6.4.1

### Desired functionality
I am going to use this plugin in my project which is an angular app.
As this package using ```"href"``` for redirection so it defeat the angular concept of single page application so i need a way to replace ```"href"``` with ```"routerLink"``` to full fill requirement of single page application without hard reloading only dom change by js

This is a very good package and i appreciate your work.

Please implement this feature as soon as possible.

Thanks in advance,
Siddharth Jaiswal

**Comment by AnthonyNahas** [comment]
routerLink is not supported by the native linkifyjs library! For that reason it's not so easy to implement that feature! 

I am sorry!
