### ISSUE TITLE
Mentions not only in English language

### ISSUE THREAD

**Issue by sergey-karlo** [AnthonyNahas/ngx-linkifyjs#132]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions
Angular CLI: 8.3.19
Node: 10.16.3
OS: darwin x64
Angular: 8.2.14

### Repro steps
Input different from English language characters after @ 

### Desired functionality
It would be great to linkify such entries also

**Comment by sergey-karlo** [comment]
Seems linkifyjs doesn't support it itself so possibly issue should be closed

**Comment by AnthonyNahas** [comment]
that's right!
