### ISSUE TITLE
Feature Request: Open Links in New Tab (target: _blank)

### ISSUE THREAD

**Issue by logan-jobzmall** [AnthonyNahas/ngx-linkifyjs#44]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality

It would be nice to either on a case-by-case or global basis, have all linkify links open in a new tab. I didn't see this in docs and I think it would be nice to have.

**Comment by AnthonyNahas** [comment]
[ngx-linkifyjs v1.3.0](https://www.npmjs.com/package/ngx-linkifyjs) has been released!

tell me if that could help you
