### ISSUE TITLE
Not working when hashtag written in Arabic

### ISSUE THREAD

**Issue by m7ammad7assan** [AnthonyNahas/ngx-linkifyjs#68]
When write hashtag in Arabic such as

#حاسوبيات

It won't linkfyit and I tested this in your demo.

**Comment by AnthonyNahas** [comment]
Oh! This issue is rather related to the internal linkifyjs library! 

I would suggest to open the issue in [this](https://github.com/SoapBox/linkifyjs) project, since ngx-linkifyjs is just an angular wrapper of the linkifyjs package!

tekram 3aynak 🍻
