### ISSUE TITLE
IgnoreTags does not ignore <a> tag.

### ISSUE THREAD

**Issue by sachin5590** [AnthonyNahas/ngx-linkifyjs#75]
- [X] bug report 

### OS and Version?
> macOS(El Capitan: 10.11.6)

### Versions
Output from: `ng --version: 7.2.5`

### Repro steps
I have an arbitrary html which also has 'a' tags in it. So I added a tag in ignoreTags array, so that linkify should not process it. But it is still processing it.

### Desired functionality
Suppose I have a string: 'I have a `<a href="http://www.example.com">website</a>` with url http://www.example.com'.

The output I expect after applying linkifyjs is:
Suppose I have a string: 'I have a `<a href="http://www.example.com">website</a>` with url `<a href="http://www.example.com">http://www.example.com</a>`'.

**Comment by AnthonyNahas** [comment]
please consider to open the issue in the native linkifyjs project [here](https://github.com/SoapBox/linkifyjs)

this project is only an angular wrapper

thank you
